# Generated by Django 4.2.4 on 2023-11-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogUser',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False, unique=True, verbose_name='用户名')),
                ('password', models.CharField(max_length=15, verbose_name='密码')),
                ('gender', models.IntegerField(choices=[(0, '女'), (1, '男'), (2, '未知')], null=True, verbose_name='性别')),
                ('career', models.CharField(max_length=30, null=True, verbose_name='职业')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('createTime', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
