# Generated by Django 4.2.4 on 2023-11-15 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0009_alter_bloguser_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='createTime',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 15, 12, 18, 20, 787343, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='gender',
            field=models.IntegerField(choices=[(0, '女'), (1, '男'), (2, '未知')], default=0, verbose_name='性别'),
            preserve_default=False,
        ),
    ]
