# Generated by Django 4.2.4 on 2023-11-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0010_alter_bloguser_createtime_alter_bloguser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='createTime',
            field=models.DateField(verbose_name='创建时间'),
        ),
    ]
