# Generated by Django 4.2.4 on 2023-11-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0011_alter_bloguser_createtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='createTime',
            field=models.DateField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
