# Generated by Django 4.2.4 on 2023-11-16 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0019_alter_bloguser_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('classification', models.IntegerField(primary_key=True, serialize=False, verbose_name='分类ID')),
                ('title', models.CharField(max_length=10, unique=True, verbose_name='分类名称')),
                ('status', models.CharField(choices=[(0, '未通过'), (1, '通过'), (2, '审核中')], default=2, max_length=1, verbose_name='分类状态')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('admin', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='审核员用户名')),
                ('password', models.CharField(max_length=15, verbose_name='密码')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='博客ID')),
                ('title', models.CharField(max_length=255, verbose_name='博客标题')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('lable', models.CharField(max_length=20, verbose_name='博客标签')),
                ('summary', models.TextField(verbose_name='博客简介')),
                ('text', models.TextField(verbose_name='博客内容')),
                ('status', models.CharField(choices=[(0, '未通过'), (1, '通过'), (2, '审核中')], default='2', max_length=1, verbose_name='博客状态')),
                ('feedback', models.TextField(verbose_name='反馈内容')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.review')),
                ('classification', models.ManyToManyField(to='app01.category')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.bloguser')),
            ],
        ),
        migrations.CreateModel(
            name='Attached',
            fields=[
                ('attachid', models.IntegerField(primary_key=True, serialize=False, verbose_name='附属ID')),
                ('like', models.IntegerField(null=True, verbose_name='点赞')),
                ('dislike', models.IntegerField(null=True, verbose_name='点踩')),
                ('collect', models.IntegerField(null=True, verbose_name='收藏')),
                ('comment', models.TextField(null=True, verbose_name='评论')),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.blog')),
            ],
        ),
    ]
