# Generated by Django 4.2.4 on 2023-11-16 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0020_category_review_blog_attached'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attached',
            name='attachid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='附属ID'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='博客ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='classification',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='分类ID'),
        ),
    ]
