# Generated by Django 4.2.7 on 2024-02-26 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0022_alter_blog_createtime_alter_bloguser_createtime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='feedback',
            field=models.TextField(null=True, verbose_name='反馈内容'),
        ),
    ]
