# Generated by Django 4.2.7 on 2024-02-28 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0023_alter_blog_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app01.review'),
        ),
    ]
