# Generated by Django 4.2.7 on 2024-02-29 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0024_alter_blog_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='lable',
        ),
    ]
