# Generated by Django 4.2.7 on 2024-03-07 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0025_remove_blog_lable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='token')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app01.bloguser')),
            ],
        ),
    ]
