# Generated by Django 4.2.7 on 2024-03-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0026_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='classification',
            field=models.ManyToManyField(blank=True, to='app01.category'),
        ),
    ]
