# Generated by Django 4.2.7 on 2024-03-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0029_blog_comment_count_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dislikes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='不喜欢数量'),
        ),
        migrations.AddField(
            model_name='comment',
            name='favorites_count',
            field=models.PositiveIntegerField(default=0, verbose_name='收藏数量'),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='点赞数量'),
        ),
    ]
