# Generated by Django 4.2.7 on 2024-03-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0030_comment_dislikes_count_comment_favorites_count_and_more'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='comment',
        #     name='favorites_count',
        # ),
        # migrations.AddField(
        #     model_name='comment',
        #     name='parent_comment',
        #     field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app01.comment', verbose_name='父评论'),
        # ),
        migrations.AlterField(
            model_name='attached',
            name='comment',
            field=models.IntegerField(null=True, verbose_name='评论'),
        ),
        migrations.CreateModel(
            name='Bloglike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.BooleanField(default=False, verbose_name='点赞')),
                ('dislike', models.BooleanField(default=False, verbose_name='点踩')),
                ('save', models.BooleanField(default=False, verbose_name='收藏')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.blog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.bloguser')),
            ],
        ),
    ]
