# Generated by Django 4.2.7 on 2024-03-13 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0031_remove_comment_favorites_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglike',
            name='id',
        ),
        migrations.AlterField(
            model_name='bloglike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='likes', serialize=False, to='app01.bloguser'),
        ),
    ]
