# Generated by Django 4.2.7 on 2024-03-13 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0032_remove_bloglike_id_alter_bloglike_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglike',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='likes', serialize=False, to='app01.bloguser'),
        ),
    ]
