# Generated by Django 4.2.7 on 2024-03-13 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0033_alter_bloglike_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attached',
            old_name='id',
            new_name='blog',
        ),
        migrations.AlterField(
            model_name='bloglike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='likes', serialize=False, to='app01.bloguser'),
        ),
    ]
