# Generated by Django 4.2.7 on 2024-03-13 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0034_rename_id_attached_blog_alter_bloglike_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='favorites_count',
        ),
    ]
