# Generated by Django 4.2.7 on 2024-03-13 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0035_remove_comment_favorites_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglike',
            name='user',
        ),
        migrations.AddField(
            model_name='bloglike',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bloglike',
            name='username',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='app01.bloguser'),
            preserve_default=False,
        ),
    ]
