# Generated by Django 4.2.7 on 2024-03-13 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0036_remove_bloglike_user_bloglike_id_bloglike_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloglike',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app01.bloguser'),
        ),
    ]
