# Generated by Django 4.2.7 on 2024-03-15 05:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0037_alter_bloglike_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attached',
            name='blog',
            field=models.ForeignKey(db_column='id_id', on_delete=django.db.models.deletion.CASCADE, to='app01.blog'),
        ),
    ]
