# Generated by Django 4.2.7 on 2024-03-17 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0042_alter_attached_collect_alter_attached_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attached',
            name='collect',
            field=models.IntegerField(default=0, verbose_name='收藏'),
        ),
        migrations.AlterField(
            model_name='attached',
            name='comment',
            field=models.IntegerField(default=0, verbose_name='评论'),
        ),
        migrations.AlterField(
            model_name='attached',
            name='dislike',
            field=models.IntegerField(default=0, verbose_name='点踩'),
        ),
        migrations.AlterField(
            model_name='attached',
            name='like',
            field=models.IntegerField(default=0, verbose_name='点赞'),
        ),
    ]
