# Generated by Django 4.2.7 on 2024-03-18 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0043_alter_attached_collect_alter_attached_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='comment_count',
        ),
    ]
